[package]
name = "bi2a_flash"
version.workspace = true
edition.workspace = true

[[bin]]
name = "bi2a_flash"
path = "src/main.rs"

[dependencies]
bi2a_protocol = { workspace = true }
clap = { workspace = true }
reader = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
hex = "0.4.3"