// It has been fully generated by Copilot.
// Who implements its own slightly modified LZSS decompressor??

pub struct AcLzInflate {
    /// Sliding window / output ring buffer (4096 bytes, wraps at 0xFFF)
    ring_buf: [u8; 4096],
    /// +0x1018: output read head when draining (state 3), or ref_byte0 during back-ref decode (state 2)
    out_start: u16,
    /// +0x101a: nonzero guard for get_char (set to output length; not used as countdown)
    count: u8,
    /// +0x101c: bit-shift flag register; 0xFF00 is the sentinel tracking remaining bits
    flag_reg: u16,
    /// +0x101e: ring buffer write head (advances, wraps at 0xFFF)
    write_pos: u16,
    /// +0x1020: state machine (0=await flag, 1=await data, 2=await ref byte2, 3=output ready)
    state: u8,
}

impl AcLzInflate {
    pub fn new() -> Self {
        let mut lz = Self {
            ring_buf: [0u8; 4096],
            out_start: 0,
            count: 0,
            flag_reg: 0,
            write_pos: 0xFEE,
            state: 0,
        };
        lz.clear();
        lz
    }

    /// Resets the decompressor. Pre-fills the first 0xFEE ring buffer bytes with 0x00
    /// (Okumura warm-start) so back-references into pre-history produce a known pattern.
    pub fn clear(&mut self) {
        self.ring_buf[..0xFEE].fill(0x00);
        self.count = 0;
        self.flag_reg = 0;
        self.write_pos = 0xFEE;
        self.state = 0;
    }

    /// Feed one compressed byte (or pass a negative value to signal EOF).
    /// Returns `true`  when output bytes are ready — drain with `get_char` until it returns -1.
    /// Returns `false` when more input is needed.
    pub fn put_char(&mut self, param: i32) -> bool {
        match self.state {
            0 => {
                if param < 0 {
                    self.state = 3;
                    return true;
                }
                self.state = 1;
                // If the sentinel has shifted entirely out of the high byte, all 8 flag
                // bits have been consumed: load param as the next flag byte.
                if self.flag_reg & 0xFF00 == 0 {
                    self.flag_reg = (param as u16) | 0xFF00;
                    return false;
                }
                // flag_reg still has remaining bits; param is already a data byte.
                self.state1(param)
            }
            1 => self.state1(param),
            2 => self.state2(param),
            _ => {
                // Called while output is pending (drain violation) or unknown state.
                self.count = 0;
                self.state = 3;
                true
            }
        }
    }

    fn state1(&mut self, param: i32) -> bool {
        if param < 0 {
            self.state = 3;
            return true;
        }
        if self.flag_reg & 1 != 0 {
            // Flag bit = 1: literal byte
            self.flag_reg >>= 1;
            self.count = 1;
            self.out_start = self.write_pos;
            self.ring_buf[self.write_pos as usize] = param as u8;
            self.write_pos = (self.write_pos + 1) & 0xFFF;
            self.state = 3;
            true
        } else {
            // Flag bit = 0: back-reference; stash the high byte, wait for the low byte.
            // Note: the flag bit is consumed in state2, not here.
            self.state = 2;
            self.out_start = param as u16; // ref_byte0 reuses the out_start field
            false
        }
    }

    fn state2(&mut self, param: i32) -> bool {
        if param < 0 {
            self.state = 3;
            return true;
        }

        // Reassemble the 16-bit token: high byte was stashed in out_start, low byte is param.
        let token = ((self.out_start as u16 & 0xFF) << 8) | (param as u16 & 0xFF);
        //  token[15:12] = length_code  (0–15)  →  match_len = length_code + 3  (3–18)
        //  token[11:0]  = match_start           →  absolute ring buffer index 0–4095
        let match_start = (token & 0x0FFF) as usize;
        let match_len = (token >> 12) + 3;

        self.flag_reg >>= 1; // consume the flag bit that was deferred from state1
        self.count = match_len as u8;
        self.out_start = self.write_pos; // mark where output begins for get_char

        // Copy match_len bytes from match_start, wrapping in the ring buffer.
        // Reading byte-by-byte before writing makes overlapping copies (run-length patterns) work correctly.
        let mut src = match_start;
        for _ in 0..match_len {
            let b = self.ring_buf[src];
            src = (src + 1) & 0xFFF;
            self.ring_buf[self.write_pos as usize] = b;
            self.write_pos = (self.write_pos + 1) & 0xFFF;
        }

        self.state = 3;
        true
    }

    /// Returns the next decompressed byte (0–255).
    /// Returns -1 when the current token is fully drained; state resets to 0 — resume calling `put_char`.
    /// Returns -2 when not ready (state ≠ 3, or called out of order).
    pub fn get_char(&mut self) -> i32 {
        if self.state != 3 || self.count == 0 {
            return -2;
        }
        // out_start catches up to write_pos once all written bytes have been read.
        if self.out_start == self.write_pos {
            self.count = 0;
            self.state = 0;
            return -1;
        }
        let b = self.ring_buf[self.out_start as usize];
        self.out_start = (self.out_start + 1) & 0xFFF;
        b as i32
    }

    /// Convenience wrapper: fully decompresses `input` and returns the output bytes.
    pub fn decompress(input: &[u8]) -> Vec<u8> {
        let mut lz = Self::new();
        let mut output = Vec::new();

        let drain = |lz: &mut Self, output: &mut Vec<u8>| {
            loop {
                match lz.get_char() {
                    b if b >= 0 => output.push(b as u8),
                    _ => break,
                }
            }
        };

        for &byte in input {
            if lz.put_char(byte as i32) {
                drain(&mut lz, &mut output);
            }
        }

        // Signal EOF: flushes any token interrupted mid-stream.
        if lz.put_char(-1) {
            drain(&mut lz, &mut output);
        }

        output
    }
}
