[package]
name = "bio2_ident"
version.workspace = true
edition.workspace = true

[[bin]]
name = "bio2_ident"
path = "src/main.rs"

[dependencies]
bi2a_protocol = { workspace = true }
bi2x_protocol = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
reader = { workspace = true }